// Generated by https://quicktype.io

export interface AncientOS {
	device_codename: string;
	maintainer: string;
	rom_support: string;
	device_supportgp_url: string;
	changelog_url: string;
	date_updated: string;
	download_url: string;
	phone_url: string;
}
