//https://github.com/PixysOS/official_devices/blob/master/devices.json
// Generated by https://quicktype.io

import { UpdateFunction } from './mod.ts';

export interface PixyOS {
	codename: string;
	brand: string;
	name: string;
	specs: Specs;
	supported_bases: SupportedBasis[];
}

export interface Specs {
	battery: number;
	camera: string;
	cpu: string;
	display: string;
	ram: string;
}

export interface SupportedBasis {
	name: Name;
	xda_thread?: string;
	supported_edition: SupportedEdition[];
	status?: string;
}

export enum Name {
	Eleven = 'eleven',
	Ten = 'ten',
	Twelve = 'twelve',
}

export enum SupportedEdition {
	Gapps = 'gapps',
	Vanilla = 'vanilla',
}

export const pixyos: UpdateFunction = async () => {
	const devices: PixyOS[] = await fetch(
		'https://github.com/PixysOS/official_devices/blob/master/devices.json?raw=true'
	).then((r) => r.json());

	return devices.map((x) => {
		return {
			brand: x.brand,
			name: x.name,
			codename: x.codename,
			rom: {
				id: 'pixyos',
			},
		};
	});
};
