git clone https://github.com/syberia-project/official_devices ota/official_devices
git clone https://github.com/Havoc-OS/OTA ota/havocota
git clone https://github.com/crdroidandroid/android_vendor_crDroidOTA ota/android_vendor_crDroidOTA
git clone https://github.com/Spark-Devices/OTA ota/sparkota
git clone https://github.com/PixelExtended/OTA ota/pixelextendedota
git clone https://github.com/LineageOS/lineage_wiki ota/lineage_wiki
git clone https://github.com/PixelExperience/official_devices ota/pixelexperience
git clone https://github.com/AOSPK/official_devices ota/oaspk
git clone https://github.com/RevengeOS-Devices/official_devices ota/revenge
git clone https://github.com/ingbrzy/Xiaomi.eu-MIUIv12-XML-Compare ota/xiaomieu
